### Get request with a header
GET http://127.0.0.1:8080/demo.do?action=sayHello
Accept: application/json

### Get request with parameter
GET https://httpbin.org/get?show_env=1
Accept: application/json

### Get request with environment variables
GET {{host}}/get?show_env={{show_env}}
Accept: application/json

###